/*

Insert fuer Tabelle kontext.hochschule

Autor:
  Eike Schroeder

Skriptinfo:
 Insert fuer Tabelle hochschule des Schemas kontext.

*/

-- Tabelle fuer Hochschulen, verkuepft mit Bundesland, Typ und Traegerschaft

INSERT INTO hochschule (id, name, name_kurz, bundesland_id, hochschule_typ_id, hochschule_traegerschaft_id) VALUES
(10105, 'Albert-Ludwigs-Universität Freiburg', 'U Freiburg i.Br.', 1, 1, 1),
(10110, 'Ruprecht-Karls-Universität Heidelberg', 'U Heidelberg', 1, 1, 1),
(10115, 'Universität Hohenheim', 'U Hohenheim', 1, 1, 1),
(10120, 'Karlsruher Institut für Technologie', 'Karlsruher Institut für Technologie (KIT) - Bereich Hochschule (U)', 1, 1, 1),
(10125, 'Universität Konstanz', 'U Konstanz', 1, 1, 1),
(10130, 'Universität Mannheim', 'U Mannheim', 1, 1, 1),
(10135, 'Universität Stuttgart', 'U Stuttgart', 1, 1, 1),
(10140, 'Eberhard Karls Universität Tübingen', 'U Tübingen', 1, 1, 1),
(10145, 'Universität Ulm', 'U Ulm', 1, 1, 1),
(10160, 'Zeppelin Universität gemeinnützige GmbH', 'Zeppelin Universität Friedrichshafen (Priv. U)', 1, 1, 2),
(10170, 'Freie Hochschule Stuttgart Seminar für Waldorfpädagogik', 'Freie Hochschule Stuttgart, Seminar für Waldorfpädagogik (Priv. U)', 1, 1, 2),
(10175, 'Hochschule für Jüdische Studien', 'H für jüdische Studien Heidelberg (Kirchl. U)', 1, 1, 2),
(10205, 'Universität Augsburg', 'U Augsburg', 2, 1, 1),
(10210, 'Otto-Friedrich-Universität Bamberg', 'U Bamberg', 2, 1, 1),
(10215, 'Universität Bayreuth', 'U Bayreuth', 2, 1, 1),
(10220, 'Katholische Universität Eichstätt-Ingolstadt', 'Kath. U Eichstätt-Ingolstadt (Kirchl. U)', 2, 1, 3),
(10225, 'Friedrich-Alexander Universität Erlangen-Nürnberg', 'U Erlangen-Nürnberg', 2, 1, 1),
(10230, 'Ludwig-Maximilians-Universität München', 'U München', 2, 1, 1),
(10235, 'Technische Universität München', 'TU München in München, Straubing, Garching und Weihenstephan', 2, 1, 1),
(10240, 'Universität der Bundeswehr München', 'U der Bundeswehr München', 2, 1, 1),
(10250, 'Universität Passau', 'U Passau', 2, 1, 1),
(10255, 'Universität Regensburg', 'U Regensburg', 2, 1, 1),
(10260, 'Julius-Maximilians-Universität Würzburg', 'U Würzburg', 2, 1, 1),
(10305, 'Freie Universität Berlin', 'FU Berlin', 4, 1, 1),
(10310, 'Technische Universität Berlin', 'TU Berlin', 4, 1, 1),
(10315, 'Charité - Universitätsmedizin Berlin', 'Charité', 4, 1, 1),
(10320, 'Humboldt-Universität zu Berlin', 'Humboldt-Universität Berlin', 4, 1, 1),
(10325, 'ESCP Europe Wirtschaftshochschule Berlin', 'ESCP Europe Wirtschaftshochschule Berlin (Priv. U)', 4, 1, 2),
(10330, 'ESMT European School of Management and Technology GmbH', 'Europ. School of Management and Technology, Berlin (Priv. U)', 4, 1, 2),
(10335, 'Hertie School of Governance GmbH', 'Hertie School of Governance Berlin (Priv. U)', 4, 1, 2),
(10340, 'Steinbeis-Hochschule Berlin GmbH (SHB)', 'Steinbeis-H Berlin (Priv. U)', 4, 1, 2),
(10350, 'Internationale Psychoanalytische Universität Berlin gGmbH', 'International Psychoanalytic Uni. Berlin (Priv.U)', 4, 1, 2),
(10355, 'Psychologische Hochschule Berlin gGmbH', 'Psychologische Hochschule Berlin (Priv. U)', 4, 1, 2),
(10360, 'Bard College Berlin, a Liberal Arts University gGmbH', 'Bard College Berlin, A Liberal Arts University (Priv. U)', 4, 1, 2),
(10365, 'German International University (GIU)', 'German International University Berlin (Priv. U)', 4, 1, 2),
(10407, 'Brandenburgische Technische Universität Cottbus-Senftenberg', 'Brandenburgische TU Cottbus-Senftenberg', 3, 1, 1),
(10410, 'Europa-Universität Viadrina', 'Europa-U Viadrina Frankfurt (Oder)', 3, 1, 1),
(10415, 'Universität Potsdam', 'U Potsdam', 3, 1, 1),
(10420, 'Medizinische Hochschule Brandenburg Theodor Fontane (MHB)', 'Medizinische Hochschule Brandenburg in Neuruppin (Priv. U)', 3, 1, 2),
(10425, 'Filmuniversität Babelsberg KONRAD WOLF', 'Filmuniversität Babelsberg', 3, 1, 1),
(10430, 'HMU Health and Medical University', 'HMU Health and Medical University Potsdam (Priv.U)', 3, 1, 2),
(10505, 'Universität Bremen', 'U Bremen', 5, 1, 1),
(10510, 'Jacobs University Bremen gGmbH', 'Jacobs University Bremen (Priv. U)', 5, 1, 2),
(10605, 'Universität Hamburg', 'U Hamburg', 6, 1, 1),
(10610, 'Technische Universität Hamburg', 'TU Hamburg-Harburg', 6, 1, 1),
(10615, 'HafenCity Universität Hamburg Universität für Baukunst und Metropolenentwicklung', 'Hafencity Universität Hamburg', 6, 1, 1),
(10620, 'Helmut-Schmidt-Universität Universität der Bundeswehr Hamburg', 'Helmut-Schmidt-Universität Hamburg', 6, 1, 1),
(10625, 'Bucerius Law School gGmbH Hochschule für Rechtswissenschaft', 'Bucerius Law School Hamburg (Priv. U)', 6, 1, 2),
(10630, 'KÜHNE Logistik Universität Wissenschaftliche Hochschule für Logistik und Unternehmensführung', 'KLU Kühne Logistics University (Priv. U)', 6, 1, 2),
(10705, 'Technische Universität Darmstadt', 'TU Darmstadt', 7, 1, 1),
(10710, 'Goethe-Universität Frankfurt am Main', 'U Frankfurt a.M.', 7, 1, 1),
(10715, 'Justus-Liebig-Universität Gießen', 'U Gießen', 7, 1, 1),
(10725, 'Universität Kassel', 'U Kassel', 7, 1, 1),
(10730, 'Philipps-Universität Marburg', 'U Marburg', 7, 1, 1),
(10735, 'Frankfurt School of Finance & Management gGmbH', 'Frankfurt School of Finance & Management-HfB (Priv. U)', 7, 1, 2),
(10740, 'EBS Universität für Wirtschaft und Recht', 'EBS U für Wirtschaft und Recht (Priv. U)', 7, 1, 2),
(10805, 'Universität Greifswald', 'U Greifswald', 8, 1, 1),
(10810, 'Universität Rostock', 'U Rostock', 8, 1, 1),
(10905, 'Technische Universität Braunschweig', 'TU Braunschweig', 9, 1, 1),
(10910, 'Technische Universität Clausthal', 'TU Clausthal', 9, 1, 1),
(10915, 'Georg-August-Universität Göttingen', 'U Göttingen', 9, 1, 1),
(10920, 'Leibniz Universität Hannover', 'U Hannover', 9, 1, 1),
(10925, 'Medizinische Hochschule Hannover (MHH)', 'Medizinische H Hannover (U)', 9, 1, 1),
(10930, 'Stiftung Tierärztliche Hochschule Hannover', 'Tierärztliche H Hannover (U)', 9, 1, 1),
(10935, 'Stiftung Universität Hildesheim', 'U Hildesheim', 9, 1, 1),
(10940, 'Leuphana Universität Lüneburg', 'U Lüneburg', 9, 1, 1),
(10945, 'Carl von Ossietzky Universität Oldenburg', 'U Oldenburg', 9, 1, 1),
(10950, 'Universität Osnabrück', 'U Osnabrück', 9, 1, 1),
(10955, 'Universität Vechta', 'Universität Vechta', 9, 1, 1),
(11005, 'RWTH Aachen', 'TH Aachen (U)', 10, 1, 1),
(11010, 'Universität Bielefeld', 'U Bielefeld', 10, 1, 1),
(11015, 'Ruhr-Universität Bochum', 'U Bochum', 10, 1, 1),
(11020, 'Rheinische Friedrich-Wilhelms- Universität Bonn', 'U Bonn', 10, 1, 1),
(11025, 'Technische Universität Dortmund', 'U Dortmund', 10, 1, 1),
(11030, 'Heinrich-Heine-Universität Düsseldorf', 'U Düsseldorf', 10, 1, 1),
(11034, 'Universität Duisburg-Essen', 'U Duisburg-Essen', 10, 1, 1),
(11040, 'FernUniversität in Hagen', 'Fernuniversität Hagen', 10, 1, 1),
(11045, 'Universität zu Köln', 'U Köln', 10, 1, 1),
(11050, 'Deutsche Sporthochschule Köln', 'Deutsche Sporthochschule Köln (U)', 10, 1, 1),
(11055, 'Westfälische Wilhelms-Universität Münster', 'U Münster', 10, 1, 1),
(11060, 'Universität Paderborn', 'U Paderborn', 10, 1, 1),
(11065, 'Universität Siegen', 'U Siegen', 10, 1, 1),
(11070, 'Bergische Universität Wuppertal', 'U Wuppertal', 10, 1, 1),
(11075, 'Private Universität Witten/Herdecke gGmbH', 'Universität Witten-Herdecke (Priv. U)', 10, 1, 2),
(11105, 'Technische Universität Kaiserslautern', 'TU Kaiserslautern', 11, 1, 1),
(11110, 'Universität Koblenz-Landau', 'U Koblenz-Landau', 11, 1, 1),
(11115, 'Johannes Gutenberg-Universität Mainz', 'U Mainz', 11, 1, 1),
(11125, 'Deutsche Universität für Verwaltungs- wissenschaften Speyer', 'Deutsche Universität für Verwaltungswissenschaften Speyer', 11, 1, 1),
(11130, 'Universität Trier', 'U Trier', 11, 1, 1),
(11135, 'WHU - Otto Beisheim School of Management', 'Wissenschaftliche H für Unternehmensführung, Vallendar (Priv. U)', 11, 1, 2),
(11205, 'Universität des Saarlandes', 'U des Saarlandes Saarbrücken', 12, 1, 1),
(11305, 'Technische Universität Chemnitz', 'TU Chemnitz', 13, 1, 1),
(11310, 'Technische Universität Dresden', 'TU Dresden', 13, 1, 1),
(11320, 'Technische Universität Bergakademie Freiberg', 'TU Bergakademie Freiberg', 13, 1, 1),
(11325, 'Universität Leipzig', 'U Leipzig', 13, 1, 1),
(11340, 'Dresden International University GmbH', 'DIU-Dresden International University (Priv. U)', 13, 1, 2),
(11345, 'HHL Leipzig Graduate School of Management', 'HHL Leipzig Graduate School of Management (Priv. U)', 13, 1, 2),
(11405, 'Martin-Luther-Universität Halle-Wittenberg', 'U Halle', 14, 1, 1),
(11410, 'Otto-von-Guericke-Universität Magdeburg', 'U Magdeburg', 14, 1, 1),
(11505, 'Europa-Universität Flensburg', 'EUF Europa-Universität Flensburg', 15, 1, 1),
(11510, 'Christian-Albrechts-Universität zu Kiel', 'U Kiel', 15, 1, 1),
(11515, 'Universität zu Lübeck', 'U Lübeck', 15, 1, 1),
(11605, 'Universität Erfurt', 'U Erfurt', 16, 1, 1),
(11610, 'Technische Universität Ilmenau', 'TU Ilmenau', 16, 1, 1),
(11615, 'Friedrich-Schiller-Universität Jena', 'U Jena', 16, 1, 1),
(11620, 'Bauhaus-Universität Weimar', 'Bauhaus-U Weimar', 16, 1, 1),
(30105, 'Pädagogische Hochschule Freiburg', 'PH Freiburg i.Br.', 1, 2, 1),
(30110, 'Pädagogische Hochschule Heidelberg', 'PH Heidelberg', 1, 2, 1),
(30115, 'Pädagogische Hochschule Karlsruhe', 'PH Karlsruhe', 1, 2, 1),
(30120, 'Pädagogische Hochschule Ludwigsburg', 'PH Ludwigsburg', 1, 2, 1),
(30125, 'Pädagogische Hochschule Schwäbisch Gmünd', 'PH Schwäbisch Gmünd', 1, 2, 1),
(30130, 'Pädagogische Hochschule Weingarten', 'PH Weingarten', 1, 2, 1),
(40210, 'Hochschule für Philosophie München', 'H für Philosophie München (Kirchl.-Theol. H)', 2, 3, 3),
(40215, 'Augustana-Hochschule Neuendettelsau', 'Augustana-H Neuendettelsau (Kirchl.-Theol. H)', 2, 3, 3),
(40705, 'Philosophisch-Theologische Hochschule Sankt Georgen', 'Phil.-Theol. H Frankfurt a.M. (Kirchl.-Theol. H)', 7, 3, 3),
(40710, 'Theologische Fakultät Fulda', 'Theol. Fakultät Fulda (Kirchl.-Theol. H)', 7, 3, 3),
(40715, 'Lutherische Theologische Hochschule', 'Luth.-Theologische H Oberursel (Kirchl.-Theol. H)', 7, 3, 3),
(40717, 'Theologische Hochschule Ewersbach Kronberg-Forum', 'Theologische H Ewersbach in Dietzhölztal (Priv.-Theol. H)', 7, 3, 3),
(40720, 'Freie Theologische Hochschule Gießen', 'Freie Theologische H (FTH) Gießen (Priv.-Theol. H)', 7, 3, 2),
(40725, 'Evangelische Hochschule Tabor', 'Evangelische Hochschule Tabor in Marburg (Priv.-Theol. H)', 7, 3, 2),
(41012, 'Hochschule für Kirchenmusik der Evangelischen Kirche von Westfalen', 'H für Kirchenmusik der evang. Kirche von Westfalen, Herford (Kirchl.-Theol. H)', 10, 3, 3),
(41015, 'Philosophisch-Theologische Hochschule', 'Phil.-Theol. H Münster (Kirchl.-Theol. H)', 10, 3, 3),
(41020, 'Theologische Fakultät Paderborn', 'Theol. Fakultät Paderborn (Kirchl.-Theol. H)', 10, 3, 3),
(41025, 'Philosophisch-Theologische Hochschule Theologische Fakultät Sankt Augustin', 'Phil.-Theol. H St. Augustin (Kirchl.-Theol. H)', 10, 3, 3),
(41035, 'Kirchliche Hochschule Wuppertal/Bethel Hochschule für Kirche und Diakonie', 'Kirchliche Hochschule Wuppertal / Bethel (Kirchl.-Theol. H)', 10, 3, 3),
(41105, 'Theologische Fakultät Trier', 'Theol. Fakultät Trier (Kirchl.-Theol. H)', 11, 3, 3),
(41110, 'Philosophisch-Theologische Hochschule', 'Theol. H Vallendar (Kirchl.-Theol. H)', 11, 3, 3),
(41405, 'Theologische Hochschule Friedensau', 'Theol. H Friedensau (Kirchl.-Theol. H)', 14, 3, 3),
(50105, 'Hochschule für Musik Freiburg i. Br.', 'Staatl. H für Musik Freiburg i.Br. (Kunst-H)', 1, 4, 1),
(50110, 'Staatliche Akademie der Bildenden Künste', 'Staatl. Akademie der Bildenden Künste Karlsruhe (Kunst-H)', 1, 4, 1),
(50115, 'Staatliche Hochschule für Gestaltung', 'Staatl. H für Gestaltung Karlsruhe (Kunst-H)', 1, 4, 1),
(50120, 'Hochschule für Musik Karlsruhe', 'Staatl. H für Musik Karlsruhe (Kunst-H)', 1, 4, 1),
(50125, 'Staatliche Hochschule für Musik und Darstellende Kunst Mannheim', 'Staatl. H für Musik und Darstellende Kunst Mannheim (Kunst-H)', 1, 4, 1),
(50130, 'Staatliche Akademie der Bildenden Künste Stuttgart', 'Staatl. Akademie der Bildenden Künste Stuttgart (Kunst-H)', 1, 4, 1),
(50135, 'Staatliche Hochschule für Musik und Darstellende Kunst', 'Staatl. H für Musik und Darstellende Kunst Stuttgart (Kunst-H)', 1, 4, 1),
(50140, 'Staatliche Hochschule für Musik', 'Staatl. H für Musik Trossingen (Kunst-H)', 1, 4, 1),
(50205, 'Akademie der Bildenden Künste München', 'Akademie der Bildenden Künste München (Kunst-H)', 2, 4, 1),
(50210, 'Hochschule für Fernsehen und Film München', 'H für Fernsehen und Film München (Kunst-H)', 2, 4, 1),
(50215, 'Hochschule für Musik und Theater München', 'H für Musik und Theater München (Kunst-H)', 2, 4, 1),
(50220, 'Akademie der Bildenden Künste', 'Akademie der Bildenden Künste Nürnberg (Kunst-H)', 2, 4, 1),
(50225, 'Hochschule für Musik Nürnberg', 'H für Musik Nürnberg (Kunst-H)', 2, 4, 1),
(50230, 'Hochschule für Musik Würzburg', 'H für Musik Würzburg (Kunst-H)', 2, 4, 1),
(50235, 'Hochschule und Institut für ev. Kirchenmusik Bayreuth', 'H für evang. Kirchenmusik Bayreuth (Kirchl. Kunst-H)', 2, 4, 3),
(50240, 'Hochschule für Katholische Kirchenmusik und Musikpädagogik', 'H für kath. Kirchenmusik und Musikpädagogik, Regensburg (Kirchl. Kunst-H)', 2, 4, 3),
(50305, 'Universität der Künste Berlin', 'U der Künste Berlin (Kunst-H)', 4, 4, 1),
(50310, 'Weißensee Kunsthochschule Berlin', 'Kunsthochschule Berlin (Kunst-H)', 4, 4, 1),
(50315, 'Hochschule für Musik Hanns Eisler Berlin', 'H für Musik Berlin (Kunst-H)', 4, 4, 1),
(50320, 'Hochschule für Schauspielkunst Ernst Busch', 'H für Schauspielkunst Berlin (Kunst-H)', 4, 4, 1),
(50330, 'Barenboim-Said Akademie gGmbH', 'Barenboim-Said Akademie Berlin (Priv. KH)', 4, 4, 2),
(50505, 'Hochschule für Künste Bremen', 'H für Künste Bremen (Kunst-H)', 5, 4, 1),
(50605, 'Hochschule für bildende Künste (HFBK)', 'H für Bildende Künste Hamburg (Kunst-H)', 6, 4, 1),
(50610, 'Hochschule für Musik und Theater', 'H für Musik und Theater Hamburg (Kunst-H)', 6, 4, 1),
(50705, 'Staatliche Hochschule für Bildende Künste (Städelschule)', 'H für Bildende Künste - Städelschule Frankfurt a.M. (Kunst-H)', 7, 4, 1),
(50710, 'Hochschule f. Musik u Darstellende Kunst', 'H für Musik und Darstellende Kunst Frankfurt a.M. (Kunst-H)', 7, 4, 1),
(50715, 'Hochschule für Gestaltung Offenbach am Main', 'H für Gestaltung Offenbach (Kunst-H)', 7, 4, 1),
(50805, 'Hochschule für Musik und Theater', 'H für Musik und Theater Rostock (Kunst-H)', 8, 4, 1),
(50905, 'Hochschule für Bildende Künste Braunschweig', 'H für Bildende Künste Braunschweig (Kunst-H)', 9, 4, 1),
(50910, 'Hochschule für Musik, Theater und Medien Hannover', 'Hochschule für Musik, Theater und Medien Hannover (Kunst-H)', 9, 4, 1),
(51005, 'Hochschule für Musik Detmold', 'H für Musik Detmold (Kunst-H)', 10, 4, 1),
(51010, 'Kunstakademie Düsseldorf', 'Kunstakademie Düsseldorf (Kunst-H)', 10, 4, 1),
(51015, 'Robert-Schumann-Hochschule', 'Robert-Schumann-H Düsseldorf (Kunst-H)', 10, 4, 1),
(51020, 'Folkwang Universität der Künste', 'Folkwang-Hochschule Essen (Kunst-H)', 10, 4, 1),
(51025, 'Kunsthochschule für Medien', 'KH für Medien Köln (Kunst-H)', 10, 4, 1),
(51030, 'Hochschule für Musik und Tanz Köln', 'H für Musik Köln (Kunst-H)', 10, 4, 1),
(51035, 'Kunstakademie Münster Hochschule für Bildende Künste', 'Kunstakademie Münster (Kunst-H)', 10, 4, 1),
(51040, 'Alanus Hochschule gGmbH', 'Alanus H Alfter (Priv. Kunst-H)', 10, 4, 2),
(51045, 'Hochschule der bildenden Künste (HBK)', 'Hochschule der bildenden Künste (HBK) Essen (Priv. Kunst-H)', 10, 4, 2),
(51205, 'Hochschule der Bildenden Künste Saar', 'H der Bildenden Künste Saarbrücken (Kunst-H)', 12, 4, 1),
(51210, 'Hochschule für Musik Saar', 'Hochschule für Musik Saarbrücken (Kunst-H)', 12, 4, 1),
(51305, 'Hochschule für Bildende Künste Dresden', 'H für Bildende Künste Dresden (Kunst-H)', 13, 4, 1),
(51310, 'Hochschule für Kirchenmusik Dresden', 'H für Kirchenmusik der Evang.-Luth. Landeskirche Sachsens, Dresden (Kirchl. Kunst-H)', 13, 4, 3),
(51315, 'Hochschule für Musik Carl Maria von Weber Dresden', 'H für Musik Dresden (Kunst-H)', 13, 4, 1),
(51320, 'Palucca Hochschule für Tanz Dresden', 'Palucca Hochschule für Tanz Dresden (Kunst-H)', 13, 4, 1),
(51325, 'Hochschule für Grafik und Buchkunst Leipzig', 'H für Graphik und Buchkunst Leipzig (Kunst-H)', 13, 4, 1),
(51330, 'Hochschule für Musik und Theater "Felix Mendelssohn Bartholdy" Leipzig', 'H für Musik und Theater Leipzig (Kunst-H)', 13, 4, 1),
(51405, 'Burg Giebichenstein Kunsthochschule Halle', 'Burg Giebichenstein Kunsthochschule Halle (Kunst-H)', 14, 4, 1),
(51410, 'Ev. Hochschule für Kirchenmusik', 'Evang. H für Kirchenmusik Halle (Kirchl. Kunst-H)', 14, 4, 3),
(51505, 'Muthesius-Kunsthochschule', 'Muthesius Kunsthochschule Kiel (Kunst-H)', 15, 4, 1),
(51510, 'Musikhochschule Lübeck', 'Musikhochschule Lübeck (Kunst-H)', 15, 4, 1),
(51605, 'Hochschule für Musik FRANZ LISZT', 'H für Musik Weimar (Kunst-H)', 16, 4, 1),
(60103, 'Hochschule Aalen', 'Hochschule Aalen - Technik und Wirtschaft (FH)', 1, 5, 1),
(60106, 'Hochschule Albstadt-Sigmaringen', 'H Albstadt-Sigmaringen (FH)', 1, 5, 1),
(60109, 'Hochschule Biberach', 'H Biberach a. d. Riss (FH)', 1, 5, 1),
(60115, 'Hochschule Esslingen University of Applied Sciences', 'H Esslingen (FH)', 1, 5, 1),
(60118, 'Hochschule Furtwangen University of Applied Sciences', 'H Furtwangen (FH)', 1, 5, 1),
(60121, 'Hochschule Heilbronn Technik, Wirtschaft, Informatik', 'H Heilbronn (FH)', 1, 5, 1),
(60124, 'Hochschule Karlsruhe Technik und Wirtschaft', 'H Karlsruhe (FH)', 1, 5, 1),
(60127, 'Hochschule Konstanz Technik, Wirtschaft und Gestaltung', 'H Konstanz (FH)', 1, 5, 1),
(60132, 'Hochschule Mannheim', 'H Mannheim (FH)', 1, 5, 1),
(60134, 'Hochschule für Wirtschaft und Umwelt Nürtingen-Geislingen (HfWU)', 'H Nürtingen (FH)', 1, 5, 1),
(60137, 'Hochschule Offenburg', 'H Offenburg (FH)', 1, 5, 1),
(60140, 'Hochschule Pforzheim', 'H Pforzheim (FH)', 1, 5, 1),
(60142, 'DHBW Duale Hochschule Baden-Württemberg Stuttgart', 'Duale Hochschule Baden-Württemberg, Stuttgart (FH)', 1, 5, 1),
(60143, 'Hochschule Ravensburg-Weingarten', 'H Ravensburg-Weingarten (FH)', 1, 5, 1),
(60146, 'Hochschule Reutlingen', 'H für Technik und Wirtschaft Reutlingen (FH)', 1, 5, 1),
(60149, 'Hochschule für Forstwirtschaft Rottenburg', 'H für Forstwirtschaft Rottenburg (FH)', 1, 5, 1),
(60152, 'Hochschule für Gestaltung Schwäbisch Gmünd', 'H für Gestaltung Schwäbisch Gmünd (FH)', 1, 5, 1),
(60155, 'Hochschule der Medien Stuttgart', 'FH Stuttgart, H der Medien', 1, 5, 1),
(60158, 'Hochschule für Technik Stuttgart', 'Hochschule für Technik Stuttgart (FH)', 1, 5, 1),
(60161, 'Technische Hochschule Ulm', 'FH Ulm - H für Technik', 1, 5, 1),
(60163, 'Internationale Hochschule Liebenzell', 'Internationale Hochschule Liebenzell (Kirchl. FH)', 1, 5, 3),
(60166, 'Hochschule Macromedia University of Applied Sciences', 'H Macromedia Stuttgart (Priv. FH)', 1, 5, 2),
(60169, 'University of Europe for Applied Sciences', 'Europ. U of Applied Sciences (Priv.FH)', 1, 5, 2),
(60171, 'SRH Hochschule Heidelberg', 'SRH Hochschule Heidelberg (Priv. FH)', 1, 5, 2),
(60173, 'Naturwissenschaftlich-Technische Akademie Prof. Dr. Grübler gGmbH Isny', 'Naturwissenschaftlich - Technische Akademie Isny (Priv. FH)', 1, 5, 1),
(60174, 'Internationale Karlshochschule', 'Karlshochschule International University, Karlsruhe (Priv. FH)', 1, 5, 2),
(60175, 'Hochschule der Wirtschaft für Management gGmbH', 'Hochschule der Wirtschaft für Management (HdWM) Mannheim (Priv. FH)', 1, 5, 2),
(60177, 'Hochschule für Kommunikation und Gestaltung', 'Hochschule für Kommunikation und Gestaltung (Priv. FH)', 1, 5, 2),
(60179, 'SRH FernHochschule - The Mobile University', 'Fernhochschule Riedlingen (Priv. FH)', 1, 5, 2),
(60180, 'VWA-Hochschule für berufsbegleitendes Studium', 'VWA-Hochschule für berufsbegleitendes Studium Stuttgart (Priv. FH)', 1, 5, 2),
(60182, 'Allensbach Hochschule', 'Allensbach Hochschule Konstanz (Priv. FH)', 1, 5, 2),
(60183, 'AKAD University', 'AKAD Hochschule Stuttgart (Priv. Fern-FH)', 1, 5, 2),
(60185, 'media Akademie – Hochschule Stuttgart', 'media Akademie - Hochschule Stuttgart (Priv. FH)', 1, 5, 2),
(60186, 'Merz Akademie, Hochschule für Gestaltung, Kunst und Medien Stuttgart', 'Merz Akademie Hochschule für Gestaltung, Kunst und Medien, Stuttgart (Priv. FH)', 1, 5, 2),
(60189, 'Evangelische Hochschule Freiburg', 'Evang. Hochschule Freiburg (Kirchl. FH)', 1, 5, 3),
(60192, 'Theologische Hochschule Reutlingen Staatlich anerkannte Fachhochschule der Evangelisch-methodistische Kirche', 'Theologisches Seminar Reutlingen (Kirchl. FH)', 1, 5, 3),
(60195, 'Evangelische Hochschule Ludwigsburg', 'Evangelische Hochschule Ludwigsburg (Kirchl. FH)', 1, 5, 3),
(60198, 'Katholische Hochschule Freiburg Catholic University of Applied Sciences', 'Kath. Hochschule Freiburg i.Br. (Kirchl. FH)', 1, 5, 3),
(60203, 'Ostbayerische Technische Hochschule Amberg-Weiden (OTH)', 'Ostbayerische Technische Hochschule Amberg-Weiden (FH)', 2, 5, 1),
(60206, 'Hochschule Ansbach', 'Hochschule für angewandte Wissenschaften Ansbach (FH)', 2, 5, 1),
(60210, 'Technische Hochschule Aschaffenburg', 'Hochschule für angewandte Wissenschaften Aschaffenburg (FH)', 2, 5, 1),
(60213, 'Hochschule Augsburg', 'Hochschule für angewandte Wissenschaften Augsburg (FH)', 2, 5, 1),
(60215, 'Hochschule Coburg Hochschule für Angewandte Wissenschaften', 'Hochschule für angewandte Wissenschaften Coburg (FH)', 2, 5, 1),
(60220, 'Technische Hochschule Deggendorf', 'Technische Hochschule Deggendorf (FH)', 2, 5, 1),
(60225, 'Hochschule Hof', 'Hochschule für angewandte Wissenschaften Hof (FH)', 2, 5, 1),
(60228, 'Technische Hochschule Ingolstadt', 'Technische Hochschule Ingolstadt (FH)', 2, 5, 1),
(60231, 'Hochschule Kempten für angewandte Wissenschaften', 'Hochschule für angewandte Wissenschaften Kempten (FH)', 2, 5, 1),
(60234, 'Hochschule Landshut Hochschule für Angewandte Wissenschaften', 'Hochschule für angewandte Wissenschaften Landshut (FH)', 2, 5, 1),
(60238, 'Hochschule für angewandte Wissenschaften München', 'Hochschule für angewandte Wissenschaften München (FH)', 2, 5, 1),
(60241, 'Hochschule für Angewandte Wissenschaften Neu-Ulm', 'Hochschule für angewandte Wissenschaften Neu-Ulm (FH)', 2, 5, 1),
(60244, 'Technische Hochschule Nürnberg Georg Simon Ohm', 'Technische Hochschule Nürnberg Georg Simon Ohm (FH)', 2, 5, 1),
(60247, 'Ostbayerische Technische Hochschule Regensburg (OTH)', 'Ostbayerische Technische Hochschule Regensburg (FH)', 2, 5, 1),
(60250, 'Technische Hochschule Rosenheim', 'TH Rosenheim (FH)', 2, 5, 1),
(60253, 'Hochschule Weihenstephan-Triesdorf', 'H für angewandte Wissenschaften Weihenstephan-Triesdorf (FH)', 2, 5, 1),
(60257, 'Hochschule für angewandte Wissenschaften Würzburg-Schweinfurt', 'H für angewandte Wissenschaften Würzburg-Schweinfurt (FH)', 2, 5, 1),
(60259, 'Hochschule der Bayerischen Wirtschaft (HDBW) gGmbH', 'HDBW Hochschule der Bayerischen Wirtschaft für angewandte Wissenschaften (Priv. FH)', 2, 5, 2),
(60263, 'Hochschule für angewandtes Management GmbH', 'Hochschule für angewandtes Management, Ismaning (Priv. FH)', 2, 5, 2),
(60264, 'Hochschule für Angewandte Sprachen Sprachen & Dolmetscher Institut München', 'H für angewandte Sprachen, München, SDI (Priv. FH)', 2, 5, 2),
(60266, 'Munich Business School GmbH', 'Munich Business School München (Priv. FH)', 2, 5, 2),
(60267, 'Wilhelm Löhe Hochschule (WLH)', 'Wilhelm Löhe Hochschule für angewandte Wissenschaften Fürth (Priv. FH)', 2, 5, 2),
(60272, 'Evangelische Hochschule Nürnberg', 'Evang. Hochschule Nürnberg (Kirchl. FH)', 2, 5, 3),
(60275, 'Katholische Stiftungshochschule für angewandte Wissenschaften München', 'Katholische Stiftungshochschule München (Kirchl. FH)', 2, 5, 3),
(60305, 'Alice Salomon Hochschule Berlin', 'ASH für Sozialarbeit und Sozialpädagogik Berlin (FH)', 4, 5, 1),
(60310, 'Berliner Hochschule für Technik', 'Beuth Hochschule für Technik Berlin (FH)', 4, 5, 1),
(60315, 'Hochschule für Technik und Wirtschaft Berlin', 'H für Technik und Wirtschaft Berlin (FH)', 4, 5, 1),
(60320, 'Hochschule für Wirtschaft und Recht Berlin', 'HWR Berlin (FH)', 4, 5, 1),
(60333, 'Touro College Berlin', 'Touro College Berlin (Priv. FH)', 4, 5, 2),
(60334, 'BSP Business School Berlin Hochschule für Management', 'Business School Berlin Hochschule für Management (Priv. FH)', 4, 5, 2),
(60335, 'BBW Hochschule', 'bbw Hochschule Berlin (Priv. FH)', 4, 5, 2),
(60336, 'Akkon-Hochschule für Humanwissenschaften', 'Akkon Hochschule Berlin (Priv. FH)', 4, 5, 2),
(60340, 'MSB Medical School Berlin Hochschule für Gesundheit und Medizin', 'Medical School Berlin, H für Gesundheit und Medizin (Priv. FH)', 4, 5, 2),
(60345, 'DBU Digital Business University of Applied Sciences GmbH', 'Digital Busin. U of Appl. Scienc.Berlin (Priv. FH)', 4, 5, 2),
(60347, 'IB-Hochschule Berlin', 'IB-Hochschule Berlin in Berlin (Priv. FH)', 4, 5, 2),
(60349, 'HMKW Hochschule für Medien, Kommunikation und Wirtschaft', 'H für Medien, Kommunikation und Wirtschaft Berlin in Berlin (Priv. FH)', 4, 5, 2),
(60352, 'DHGS Deutsche Hochschule für Gesund- heit und Sport', 'Deutsche Hochschule für Gesundheit und Sport Berlin in Berlin (Priv. FH)', 4, 5, 2),
(60353, 'Mediadesign Hochschule für Design und Informatik GmbH', 'Mediadesign Hochschule Berlin (Priv. FH)', 4, 5, 2),
(60356, 'SRH Hochschule Berlin', 'SRH Hochschule Berlin (Priv. FH)', 4, 5, 2),
(60357, 'CODE Education GmbH', 'CODE Univ. of Applied Sciences Berlin (Priv. FH)', 4, 5, 2),
(60363, 'Internationale Hochschule für Wirtschaft, Technik und Kultur gGmbH', 'H für Wirtschaft, Technik und Kultur Berlin in Berlin (Priv. FH)', 4, 5, 2),
(60364, 'Berlin International University of Applied Sciences', 'Berlin International University of Applied Sciences (Priv. FH)', 4, 5, 2),
(60367, 'Quadriga Hochschule Berlin GmbH', 'Quadriga Hochschule Berlin (Priv. FH)', 4, 5, 2),
(60370, 'Evangelische Hochschule Berlin', 'Evangelische Hochschule Berlin (Kirchl. FH)', 4, 5, 3),
(60380, 'Katholische Hochschule für Sozialwesen Berlin', 'Katholische Hochschule für Sozialwesen Berlin (Kirchl. FH)', 4, 5, 3),
(60405, 'Technische Hochschule Brandenburg', 'Technische Hochschule Brandenburg (FH)', 3, 5, 1),
(60410, 'Hochschule für nachhaltige Entwicklung Eberswalde - HNEE', 'Hochschule für nachhaltige Entwicklung Eberswalde (FH)', 3, 5, 1),
(60420, 'Fachhochschule Potsdam', 'FH Potsdam', 3, 5, 1),
(60422, 'Fachhochschule für Sport und Management Potsdam der Europäischen Sportakademie Land Brandenburg gemeinnützige GmbH', 'FH für Sport und Management, Potsdam (Priv. FH)', 3, 5, 2),
(60425, 'Technische Hochschule Wildau', 'Technische Hochschule Wildau (FH)', 3, 5, 1),
(60430, 'Theologisches Seminar Elstal', 'Theologische Hochschule Elstal (Kirchl. FH)', 3, 5, 3),
(60435, 'Fachhochschule Clara Hoffbauer Potsdam', 'Fachhochschule Clara Hoffbauer Potsdam (Priv. FH)', 3, 5, 2),
(60440, 'XU Exponential University of Applied Sciences', 'XU Expon. U of Applied Sciences Potsdam (Priv. FH)', 3, 5, 2),
(60505, 'Hochschule Bremen', 'H Bremen (FH)', 5, 5, 1),
(60510, 'Hochschule Bremerhaven', 'H Bremerhaven (FH)', 5, 5, 1),
(60515, 'Apollon Hochschule der Gesundheitswirtschaft', 'APOLLON H der Gesundheitswirtschaft Bremen (Priv. FH)', 5, 5, 2),
(60605, 'Hochschule für Angewandte Wissenschaften Hamburg', 'H für Angewandte Wissenschaften Hamburg (FH)', 6, 5, 1),
(60615, 'Europäische Fernhochschule Hamburg GmbH', 'Europ. Fern-H Hamburg GmbH Hamburg (Priv. FH)', 6, 5, 2),
(60620, 'Hamburger Fern-Hochschule gGmbH', 'HFH Hamburger Fern-H (Priv. FH)', 6, 5, 2),
(60625, 'HSBA Hamburg School of Business Administration', 'HSBA Hamburg School of Business Admin. (Priv. FH)', 6, 5, 2),
(60630, 'Ev. Hochschule für soziale Arbeit und Diakonie', 'Evang. H für Soziale Arbeit und Diakonie, Hamburg (Kirchl. FH)', 6, 5, 3),
(60635, 'EBC Hochschule Campus Hamburg', 'EBC Euro Business College Hamburg Campus Hamburg (Priv. FH)', 6, 5, 2),
(60642, 'NBS Northern Business School', 'Northern Business School Hamburg (Priv. FH)', 6, 5, 2),
(60647, 'Brand Academy Hochschule für Design und Kommunikation', 'Brand Academy Hamburg (Priv. FH)', 6, 5, 2),
(60650, 'MSH Medical School Hamburg Fachhochschule für Gesundheit und Medizin', 'MSH Medical School Hamburg (Priv. FH)', 6, 5, 2),
(60705, 'Hochschule Darmstadt University of Applied Sciences', 'h_da - H Darmstadt (FH)', 7, 5, 1),
(60710, 'Frankfurt University of Applied Sciences', 'Frankfurt University of Applied Sciences (FH)', 7, 5, 1),
(60715, 'Hochschule Fulda', 'Hochschule Fulda (FH)', 7, 5, 1),
(60720, 'Technische Hochschule Mittelhessen', 'Technische Hochschule Mittelhessen (THM), FH', 7, 5, 1),
(60725, 'Hochschule RheinMain', 'Hochschule RheinMain (FH)', 7, 5, 1),
(60728, 'Hochschule Geisenheim University', 'Hochschule Geisenheim University (FH)', 7, 5, 1),
(60735, 'accadis Hochschule Bad Homburg', 'accadis Hochschule Bad Homburg (Priv. FH)', 7, 5, 2),
(60740, 'Wilhelm Büchner Hochschule', 'Wilhelm Büchner Hochschule Darmstadt (Priv. Fern-FH)', 7, 5, 2),
(60745, 'Provadis School of International Management and Technology AG', 'Provadis School of Intern. Management and Technology, Frankfurt a.M. (Priv. FH)', 7, 5, 2),
(60750, 'Hochschule Fresenius für Wirtschaft und Medien GmbH', 'Hochschule Fresenius Idstein in Idstein (Priv. FH)', 7, 5, 2),
(60755, 'DIPLOMA Private Hochschulgesellschaft mbH', 'DIPLOMA - FH Nordhessen (Priv. FH)', 7, 5, 2),
(60760, 'Evangelische Fachhochschule Darmstadt University of Applied Sciences', 'Evangelische Hochschule Darmstadt (EHD), (Kirchl. FH)', 7, 5, 3),
(60765, 'CVJM-Hochschule', 'CVJM-Hochschule Kassel (Priv. FH)', 7, 5, 2),
(60805, 'Hochschule Neubrandenburg', 'Hochschule Neubrandenburg (FH)', 8, 5, 1),
(60810, 'Hochschule Stralsund', 'Hochschule Stralsund (FH)', 8, 5, 1),
(60815, 'Hochschule Wismar University of Applied Sciences Technology, Business and Design', 'Hochschule Wismar (FH)', 8, 5, 1),
(60905, 'Hochschule Braunschweig-Wolfenbüttel (FH)', 'H Braunschweig-Wolfenbüttel', 9, 5, 1),
(60907, 'Hochschule Emden/Leer', 'Hochschule Emden/Leer (FH)', 9, 5, 1),
(60910, 'Hochschule Hannover', 'Hochschule Hannover (FH)', 9, 5, 1),
(60912, 'Hochschule Weserbergland', 'Hochschule Weserbergland (HSW), Hameln (Priv. FH)', 9, 5, 2),
(60915, 'HAWK Hochschule für angewandte Wissenschaft und Kunst', 'Hochschule Hildesheim/Holzminden/Göttingen (FH)', 9, 5, 1),
(60920, 'Jade Hochschule Wilhelmshaven/Oldenburg/Elsfleth', 'Hochschule Wilhelmshaven/Oldenburg/Elsfleth (FH)', 9, 5, 1),
(60925, 'Hochschule Osnabrück', 'Hochschule Osnabrück (FH)', 9, 5, 1),
(60927, 'Hochschule 21 gGmbH', 'Hochschule21, Buxtehude (Priv. FH)', 9, 5, 2),
(60930, 'Fachhochschule für Interkulturelle Theologie', 'FH für Interkulturelle Theologie Hermannsburg (Priv. FH)', 9, 5, 2),
(60935, 'PFH Private Hochschule Göttingen', 'Private Hochschule Göttingen (Priv. FH)', 9, 5, 2),
(60940, 'Fachhochschule für die Wirtschaft Hannover (FHDW)', 'Fachhochschule für die Wirtschaft Hannover (Priv. FH)', 9, 5, 2),
(60945, 'Hochschule für Künste im Sozialen', 'FH Ottersberg (Priv. FH)', 9, 5, 2),
(60950, 'Private Hochschule für Wirtschaft und Technik', 'H für Wirtschaft und Technik Vechta/Diepholz/Oldenburg (Priv. FH)', 9, 5, 2),
(60965, 'Leibniz-Fachhochschule School of Business', 'Leibniz - Fachhochschule Hannover (Priv. FH)', 9, 5, 2),
(61003, 'Fachhochschule Aachen', 'FH Aachen', 10, 5, 1),
(61006, 'Fachhochschule Bielefeld', 'FH Bielefeld', 10, 5, 1),
(61009, 'Hochschule Bochum', 'Hochschule Bochum (FH)', 10, 5, 1),
(61011, 'Hochschule für Gesundheit University of Applied Sciences', 'Hochschule für Gesundheit Bochum (FH)', 10, 5, 1),
(61012, 'Hochschule Bonn-Rhein-Sieg', 'FH Bonn-Rhein-Sieg', 10, 5, 1),
(61015, 'Fachhochschule Dortmund', 'FH Dortmund', 10, 5, 1),
(61018, 'Hochschule Düsseldorf', 'FH Düsseldorf', 10, 5, 1),
(61021, 'Westfälische Hochschule', 'FH Gelsenkirchen', 10, 5, 1),
(61022, 'Hochschule Hamm-Lippstadt', 'FH Hamm-Lippstadt', 10, 5, 1),
(61024, 'Technische Hochschule Köln', 'FH Köln', 10, 5, 1),
(61027, 'Technische Hochschule Ostwestfalen-Lippe', 'FH Ostwestfalen-Lippe', 10, 5, 1),
(61030, 'Fachhochschule Münster', 'FH Münster', 10, 5, 1),
(61033, 'Hochschule Niederrhein', 'FH Niederrhein', 10, 5, 1),
(61034, 'Hochschule Rhein-Waal', 'FH Rhein-Waal', 10, 5, 1),
(61036, 'Fachhochschule Südwestfalen', 'FH Südwestfalen', 10, 5, 1),
(61038, 'Hochschule Ruhr West', 'FH Westliches Ruhrgebiet', 10, 5, 1),
(61039, 'IUBH Internationale Hochschule GmbH IUBH University of Applied Sciences', 'Internationale Hochschule Bad Honnef-Bonn in Bad Honnef, Dortmund und Düsseldorf (Priv. FH)', 10, 5, 2),
(61042, 'Fachhochschule des Mittelstandes (FHM)', 'FH des Mittelstandes in Bielefeld, Köln und Pulheim (Priv. FH)', 10, 5, 2),
(61043, 'Fliedner Fachhochschule Düsseldorf', 'Fliedner Fachhochschule Düsseldorf (Priv. FH)', 10, 5, 2),
(61045, 'Technische Hochschule Georg Agricola Bochum', 'Technische FH (TFH) Georg Agricola zu Bochum (Priv. FH)', 10, 5, 2),
(61047, 'EBZ Business School University of Applied Sciences', 'EBZ Business School Bochum (Priv. FH)', 10, 5, 2),
(61048, 'Hochschule der Sparkassen-Finanzgruppe University of Applied Sciences - Bonn', 'H der Sparkassen-Finanzgruppe Bonn (Priv. FH)', 10, 5, 2),
(61051, 'Europäische Fachhochschule Rhein/Erft', 'Europäische FH (EUFH) in Brühl, Köln, Neuss und Rheine (Priv. FH)', 10, 5, 2),
(61054, 'International School of Management', 'International School of Management Dortmund in Dortmund und Köln (Priv. FH)', 10, 5, 2),
(61057, 'FOM Hochschule für Oekonomie & Management gemeinnützige GmbH', 'H für Ökonomie und Management Essen (Standorte in Nordrhein-Westfalen), (Priv. FH)', 10, 5, 2),
(61059, 'IST-Hochschule für Management GmbH', 'IST-Hochschule für Management Düsseldorf (Priv. FH)', 10, 5, 2),
(61060, 'SRH Hochschule für Logistik und Wirtschaft Hamm', 'SRH Hochschule für Logistik und Wirtschaft Hamm (Priv. FH)', 10, 5, 2),
(61063, 'University of Applied Sciences Europe Campus Iserlohn', 'Hochschule für angewandte Wissenschaften Europa Iserlohn (Priv. FH)', 10, 5, 2),
(61065, 'Cologne Business School (CBS) European University of Applied Sciences', 'Cologne Business School (CBS) - European University of Applied Sciences in Köln (Priv. FH)', 10, 5, 2),
(61069, 'Rheinische Fachhochschule Köln gGmbH', 'Rheinische FH Köln (Priv. FH)', 10, 5, 2),
(61070, 'HSD Hochschule Döpfer GmbH', 'HSD Hochschule Döpfer Köln (Priv. FH)', 10, 5, 2),
(61072, 'Fachhochschule der Wirtschaft Nordrhein-Westfalen gGmbH', 'FH der Wirtschaft Paderborn in Paderborn (Priv. FH)', 10, 5, 2),
(61074, 'Fachhochschule der Diakonie', 'FH der Diakonie Bielefeld-Bethel (Kirchl. FH)', 10, 5, 3),
(61075, 'Evangelische Fachhochschule Rheinland-Westfalen-Lippe', 'Evang. Hochschule Rheinland-Westfalen-Lippe, Bochum (Kirchl. FH)', 10, 5, 3),
(61078, 'Katholische Hochschule Nordrhein-Westfalen Catholic University of Applied Sciences', 'Kath. Hochschule Nordrhein-Westfalen (Kirchl. FH)', 10, 5, 3),
(61105, 'Technische Hochschule Bingen', 'Technische Hochschule Bingen (FH)', 11, 5, 1),
(61110, 'Hochschule Kaiserslautern', 'Hochschule Kaiserslautern (FH)', 11, 5, 1),
(61115, 'Hochschule Koblenz', 'Hochschule Koblenz (FH)', 11, 5, 1),
(61120, 'Hochschule für Wirtschaft und Gesellschaft Ludwigshafen', 'Hochschule Ludwigshafen am Rhein (FH)', 11, 5, 1),
(61125, 'Hochschule Mainz University of Applied Sciences', 'Hochschule Mainz (FH)', 11, 5, 1),
(61130, 'Hochschule Trier Trier University of Applied Sciences', 'Hochschule Trier (FH)', 11, 5, 1),
(61135, 'Hochschule Worms', 'Hochschule Worms (FH)', 11, 5, 1),
(61145, 'Katholische Hochschule Mainz', 'Katholische Hochschule Mainz (Kirchl. FH)', 11, 5, 3),
(61150, 'Cusanus Hochschule gGmbH', 'Cusanus Hochschule Bernkastel-Kues (Priv. FH)', 11, 5, 2),
(61205, 'Hochschule für Technik und Wirtschaft des Saarlandes', 'H für Technik und Wirtschaft des Saarlandes Saarbrücken (FH)', 12, 5, 1),
(61215, 'Deutsche Hochschule für Prävention und Gesundheitsmanagement GmbH', 'Deutsche Hochschule für Prävention und Gesundheitsmanagement, Saarbrücken (Priv. FH)', 12, 5, 2),
(61305, 'Hochschule für Technik und Wirtschaft Dresden', 'H für Technik und Wirtschaft Dresden, Hochschule für angewandte Wissenschaften (FH)', 13, 5, 1),
(61310, 'Hochschule für Technik, Wirtschaft und Kultur Leipzig', 'H für Technik, Wirtschaft und Kultur Leipzig, Hochschule für angewandte Wissenschaften (FH)', 13, 5, 1),
(61315, 'Hochschule Mittweida University of Applied Sciences', 'H Mittweida (University of Applied Sciences), Hochschule für angewandte Wissenschaften (FH)', 13, 5, 1),
(61320, 'Hochschule Zittau/Görlitz', 'H Zittau/Görlitz, Hochschule für angewandte Wissenschaften (FH)', 13, 5, 1),
(61325, 'Westsächsische Hochschule Zwickau', 'Westsächsische H Zwickau, Hochschule für angewandte Wissenschaften (FH)', 13, 5, 1),
(61355, 'Evangelische Hochschule Dresden (ehs)', 'Evangelische Hochschule Dresden (Kirchl. FH)', 13, 5, 3),
(61365, 'Fachhochschule Dresden Staatlich anerkannte Hochschule University of Applied Sciences', 'Fachhochschule Dresden (Priv. FH)', 13, 5, 2),
(61405, 'Hochschule Anhalt', 'H Anhalt (FH)', 14, 5, 1),
(61410, 'Hochschule Harz Hochschule für angewandte Wissenschaften', 'H Harz (FH)', 14, 5, 1),
(61415, 'Hochschule Magdeburg-Stendal', 'H Magdeburg-Stendal (FH)', 14, 5, 1),
(61420, 'Hochschule Merseburg', 'Hochschule Merseburg (FH)', 14, 5, 1),
(61505, 'Hochschule Flensburg University of Applied Sciences', 'Hochschule Flensburg (FH)', 15, 5, 1),
(61510, 'Fachhochschule Westküste Hochschule für Wirtschaft & Technik', 'FH Westküste, Heide', 15, 5, 1),
(61515, 'Fachhochschule Kiel', 'FH Kiel', 15, 5, 1),
(61520, 'Technische Hochschule Lübeck', 'Technische Hochschule Lübeck (FH)', 15, 5, 1),
(61525, 'Nordakademie Hochschule der Wirtschaft', 'Hochschule der Wirtschaft (Nordakademie) Elmshorn (Priv. FH)', 15, 5, 2),
(61535, 'Fachhochschule Wedel', 'FH Wedel (Priv. FH)', 15, 5, 2),
(61540, 'DHSH Duale Hochschule Schleswig-Holstein', 'DHSH - Duale Hochschule Schleswig-Holstein, Kiel (Priv. FH)', 15, 5, 2),
(61605, 'Fachhochschule Erfurt', 'FH Erfurt', 16, 5, 1),
(61610, 'Ernst-Abbe-Hochschule Jena Hochschule für angewandte Wissenschaften', 'Ernst-Abbe-Hochschule Jena (FH)', 16, 5, 1),
(61615, 'Hochschule Nordhausen University of Applied Sciences', 'Hochschule Nordhausen (FH)', 16, 5, 1),
(61620, 'Hochschule Schmalkalden', 'Hochschule Schmalkalden (FH)', 16, 5, 1),
(61640, 'SRH Fachhochschule für Gesundheit Gera gGmbH University of Applied Science', 'SRH FH für Gesundheit Gera (Priv. FH)', 16, 5, 2),
(61645, 'Duale Hochschule Gera-Eisenach', 'Duale Hochschule Gera-Eisenach (FH)', 16, 5, 1);
