---
title: "Reference"
format: html
editor: visual
---

# Hintergrund

`SVCleanR` ist ein R-Paket, das speziell dafür entwickelt wurde, das Cleaning in HEX zu vereinfachen und effizienter zu gestalten. Es unterstützt unter anderem dabei, typische Fehlerquellen und Inkonsistenzen in den Daten automatisiert zu erkennen und zu beheben. Ziel ist es, die Datenqualität zu erhöhen und den manuellen Aufwand bei der Datenaufbereitung deutlich zu reduzieren. `SVCleanR` befindet sich zurzeit in der Beta-Phase und wird fortlaufend weiterentwickelt. Alle betroffenen Kolleg\*innen sind herzlich dazu eingeladen, etwaige Funktionen, die ihnen das Cleaning erleichtern und generalisierte Probleme adressieren, in das Package einzupflegen. Sollte keine Zeit oder mangelndes Know-how dem eigenständigen Einpflegen im Wege stehen, können Funktionen auch einfach über das Issue-System des Repositories eingereicht werden.

Im folgenden finden sich für alle Funktionen des Pakets kurze Einführungen so wie interaktive Beispiele.

## `check_organisation`

Die `check_organisation`-Funktion erkennt automatisch häufige Fehlerquellen wie falsche Trennzeichen, unerwünschte Sonderzeichen und zu lange Einträge.

Konkret werden folgende Checks durchgeführt:

-   Falsche oder fehlende Trennung, z.B. `"; "` (Semikolon, Leerzeichen)\
-   Enthält das Zeichen `"|"`\
-   Enthält das Zeichen `">"`\
-   Zu lange Einträge (\> 1000 Zeichen)\
-   Überflüssige Leerzeichen\
-   Verdacht auf **Nicht-Organisationseinheiten** (z.B. Organisationseinheiten mit Pattern wie „Bachelor“, „Master“, „Diplom“ etc.)

Weiterhin werden wird die Anzahl der eindeutigen Organisationseinheiten, die Anzahl der NA-Werte und die Anzahl der fehlerhaft separierten Organisationseinheiten ausgegeben.

```{r}
devtools::load_all() # Passe den Pfad ggf. an, z.B. "../iuc" wenn das Paket im übergeordneten Verzeichnis liegt

test_data <- read.csv("data/test_data_organisation.csv", stringsAsFactors = FALSE)

# Zufällig einige NAs in der Organisationsspalte erzeugen (z.B. 5% der Zeilen)
set.seed(123) # für Reproduzierbarkeit
if ("organisation" %in% names(test_data)) {
  n <- nrow(test_data)
  na_indices <- sample(seq_len(n), size = ceiling(0.05 * n))
  test_data$organisation[na_indices] <- NA
}

# prüfen ob die Strings > 1000 Zeichen lang sind
test_organisation <- check_organisation(test_data)  
test_organisation |> View()
```